name: BedrockSignGlow
version: ${project.version}
main: com.techwiz18.bedrocksigns.BedrockSignGlow
api-version: '1.20'
depend: [ProtocolLib, floodgate]
description: Makes all signs glow for Bedrock/Floodgate players on Java servers
